### ISSUE TITLE
Gittalk can't login

### ISSUE THREAD

**Issue by iofu728** [FrogLu/blog#2]
- [x] I have searched the [issues](https://github.com/FrogLu/blog/issues/new) of this repository and believe that this is not a duplicate.

### Version
0.0.0

### Environment
chrome  73.0.3637.0

### Steps to reproduce
when I click the button of `login by github account`, the web redirect to home page instead of login page.
```vim
redirct url:  http://froglu.top/?error=redirect_uri_mismatch&error_description=The%20redirect_uri%20MUST%20match%20the%20registered%20callback%20URL%20for%20this%20application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch
```
From the url, we maybe find the error message.
When we open the chrome develop tool, we find one error `Container not found, document.getElementById: gitalk-container`. But the error don't relate to the bug.
So the comment maybe have bug.

### What is expected?
when we click login, we should redirect to login page.

### What is actually happening?

when we click login, we redirect to home page.

**Comment by iofu728** [comment]
From the redirect url we can see `error=redirect_uri_mismatch`.

It means that login_url mismatch register url in github develop.

So you only need to change the url in github develop

**Comment by FrogLu** [comment]
Thank you very much!

Now I fixed this bug with your help.

Reward you with a careful heart.
